name: CI - Build, Test, Deploy Streamlit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            cache-to=type=gha,mode=max
            cache-from=type=gha

      - name: Build Docker image
        run: docker build --cache-from=type=gha --cache-to=type=gha,mode=max -t solar-tool .

      - name: Run tests inside Docker
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          docker run --rm \
            -e OPENWEATHERMAP_API_KEY="$OPENWEATHERMAP_API_KEY" \
            -e OPENROUTER_API_KEY="$OPENROUTER_API_KEY" \
            solar-tool python -m pytest test_main.py -v --cov

      - name: Run Streamlit app in detached mode
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          docker run -d --name solar-streamlit -p 7860:7860 \
            -e OPENWEATHERMAP_API_KEY="$OPENWEATHERMAP_API_KEY" \
            -e OPENROUTER_API_KEY="$OPENROUTER_API_KEY" \
            solar-tool
          sleep 10

      - name: Smoke test Streamlit app
        run: |
          curl --fail --retry 3 --retry-delay 2 http://localhost:7860/healthz || (echo "Streamlit app did not start" && exit 1)

      - name: Stop Streamlit container
        run: |
          docker stop solar-streamlit
          docker rm solar-streamlit
